[package]
name = "gpui_transitions"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"

[dev-dependencies]
smallvec = "1.15.1"
palette = "0.7.6"
rand = "0.9.2"

[features]
default = []
transition_element = []
